version: "3"

services:
  server:
    container_name: AQtion-server
    image: kaniz0r/aqtion:v1
    ports:
      - "27910:27910/udp"
    stdin_open: true
    tty: true
    restart: on-failure:5
    # env_file:
    #   - example.env
    volumes:
      - type: volume
        source: maps
        target: /aq2server/action/maps

volumes:
  maps:

