name: ARMv7/v8
run-name: server:${{ github.event.inputs.release_tag }}-arm64 and arm32

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

jobs:      
  docker_build:
    runs-on: [self-hosted, ARM64]
    strategy:
      matrix:
        arch: ["arm64", "arm32"]
    name: "${{ matrix.arch }}:${{ github.event.inputs.release_tag }}"
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout aq2-tng
        uses: actions/checkout@v3
        with:
          repository: actionquake/aq2-tng
          path: aq2-tng
          ref: aqtion

      - name: Checkout q2pro
        uses: actions/checkout@v3
        with:
          repository: actionquake/q2pro
          path: q2pro
          ref: aqtion

      - name: Checkout q2admin
        uses: actions/checkout@v3
        with:
          repository: actionquake/q2admin
          path: q2admin
          ref: aqtion

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: |
          docker build -f Dockerfile-${{ matrix.arch }} -t aqtiongame/server:${{ github.event.inputs.release_tag }}-${{ matrix.arch }} .
          docker tag aqtiongame/server:${{ github.event.inputs.release_tag }}-${{ matrix.arch }} aqtiongame/server:latest-${{ matrix.arch }}
          docker push aqtiongame/server:${{ github.event.inputs.release_tag }}-${{ matrix.arch }}
          docker push aqtiongame/server:latest-${{ matrix.arch }}
