name: ARM64

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

jobs:      
  docker_build:
    runs-on: [self-hosted, ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: |
          docker build -t aqtiongame/server:${{ github.event.inputs.release_tag }}-arm64 .
          docker push aqtiongame/server:${{ github.event.inputs.release_tag }}-arm64