name: Docker Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

jobs:      
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: aq2world/server

      - name: Git submodule initialization
        run: |
          git submodule init && git submodule update
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: |
          docker build -t aqtiongame/server:${{ github.event.inputs.release_tag }} .
          docker push aqtiongame/server:${{ github.event.inputs.release_tag }}