name: Espionage

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

jobs:      
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: |
          docker build -f Dockerfile-ETE -t aqtiongame/espionage:${{ github.event.inputs.release_tag }} .
          docker push aqtiongame/espionage:${{ github.event.inputs.release_tag }}