on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

name: Docker Build - Multiarch
run-name: server:${{ github.event.inputs.release_tag }}

jobs:
  docker_build:
    name: "server:${{ github.event.inputs.release_tag }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Checkout aq2-tng
        uses: actions/checkout@v3
        with:
          repository: actionquake/aq2-tng
          path: aq2-tng
          ref: aqtion

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-multiarch
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ARCH=${{ matrix.arch }}
          tags: |
            aqtiongame/server:${{ github.event.inputs.release_tag }}
            aqtiongame/server:latest