on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

name: Docker Build - Multiarch FTE
run-name: server:${{ github.event.inputs.release_tag }}

jobs:
  docker_build:
    name: "server:${{ github.event.inputs.release_tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v4
      
      ## Generate navmesh zip file and upload to S3
      - name: Generate navmesh + botinfo archive
        run: |
          zip -r navmesh.zip bots

      - name: Upload navmesh to S3
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
          aws-region: 'us-east-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'navmesh.zip'
          destination-dir: 'action/bots/'
          bucket-root: '/'
      
      - name: Checkout aq2-tng
        uses: actions/checkout@v4
        with:
          repository: actionquake/aq2-tng
          path: aq2-tng
          ref: aqtion

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-fte
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            aqtiongame/server_fte:${{ github.event.inputs.release_tag }}
            aqtiongame/server_fte:latest