name: Test Container

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true
      q2pro_branch:
        description: 'q2pro branch to build from'     
        required: true
        default: 'aqtion'
      tng_branch:
        description: 'TNG branch to build from'     
        required: true
        default: 'aqtion'
      q2a_branch:
        description: 'q2admin branch to build from'     
        required: true
        default: 'aqtion'

jobs:
  docker_build:
    name: "aqtiongame/test:${{ github.event.inputs.release_tag }} - ${{ github.event.inputs.q2pro_branch }} / ${{ github.event.inputs.tng_branch }} / ${{ github.event.inputs.q2a_branch }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Checkout aq2-tng
        uses: actions/checkout@v3
        with:
          repository: actionquake/aq2-tng
          path: aq2-tng
          ref: ${{ github.event.inputs.tng_branch }}

      - name: Checkout q2pro
        uses: actions/checkout@v3
        with:
          repository: actionquake/q2pro
          path: q2pro
          ref: ${{ github.event.inputs.q2pro_branch }}

      - name: Checkout q2admin
        uses: actions/checkout@v3
        with:
          repository: actionquake/q2admin
          path: q2admin
          ref: ${{ github.event.inputs.q2a_branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: |
          docker build -t aqtiongame/test:${{ github.event.inputs.release_tag }} -f Dockerfile-dev .
          docker push aqtiongame/test:${{ github.event.inputs.release_tag }}